<?php

namespace Proxies\__CG__\tperroin\BlogSioBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Projet extends \tperroin\BlogSioBundle\Entity\Projet implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function setTeaser($teaser)
    {
        $this->__load();
        return parent::setTeaser($teaser);
    }

    public function getTeaser()
    {
        $this->__load();
        return parent::getTeaser();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setAuteur($auteur)
    {
        $this->__load();
        return parent::setAuteur($auteur);
    }

    public function getAuteur()
    {
        $this->__load();
        return parent::getAuteur();
    }

    public function setPresentation($presentation)
    {
        $this->__load();
        return parent::setPresentation($presentation);
    }

    public function getPresentation()
    {
        $this->__load();
        return parent::getPresentation();
    }

    public function setRessources($ressources)
    {
        $this->__load();
        return parent::setRessources($ressources);
    }

    public function getRessources()
    {
        $this->__load();
        return parent::getRessources();
    }

    public function setDossierTechnique($dossierTechnique)
    {
        $this->__load();
        return parent::setDossierTechnique($dossierTechnique);
    }

    public function getDossierTechnique()
    {
        $this->__load();
        return parent::getDossierTechnique();
    }

    public function setConfigSources($configSources)
    {
        $this->__load();
        return parent::setConfigSources($configSources);
    }

    public function getConfigSources()
    {
        $this->__load();
        return parent::getConfigSources();
    }

    public function setActivitesCompetences($activitesCompetences)
    {
        $this->__load();
        return parent::setActivitesCompetences($activitesCompetences);
    }

    public function getActivitesCompetences()
    {
        $this->__load();
        return parent::getActivitesCompetences();
    }

    public function setBilan($bilan)
    {
        $this->__load();
        return parent::setBilan($bilan);
    }

    public function getBilan()
    {
        $this->__load();
        return parent::getBilan();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titre', 'teaser', 'date', 'auteur', 'presentation', 'ressources', 'dossierTechnique', 'configSources', 'activitesCompetences', 'bilan');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}