<?php

namespace Sonata\NewsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CommentAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sonata\NewsBundle\Controller\CommentAdminController();
        return $instance;
    }
}
